# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 543cf18c0def53edd93db0bdf8a691e03a4bf101df17390ceffbc7fc042f0fa1cf63f049fa6fc96aff87434ab7993c438e8d509bbbcd876505da560edac090ca

test:
  secret_key_base: 362feda4b297adbba22c929af72b3a1fa47dc850cde17c218c479ca5193f89d88c52017f1f196bf39f4d23f9c803a05801921b47df5fe779980d7e187ea65d82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
